name: Build Mac DMG

on:
  workflow_dispatch:  # Manual trigger
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci || npm install
      
    - name: Build application
      run: npm run build-app

    - name: Create initial data file
      run: npm run create-initial-zip

    - name: Package for Mac (x64 only)
      run: node scripts/package-app.js darwin x64
      env:
        # Disable code signing for now (creates unsigned app)
        CSC_IDENTITY_AUTO_DISCOVERY: false
        
    - name: Create DMG (optional)
      run: |
        echo "Skipping DMG creation - .app bundle is sufficient for distribution"
        echo "The packaged .app file can be distributed directly or zipped"
      continue-on-error: true
      
    - name: Upload Mac artifacts
      uses: actions/upload-artifact@v4
      with:
        name: prayer-slides-mac
        path: |
          packaged/Prayer Slides-darwin-x64/
          installers/*.dmg
          dist/*.dmg
        retention-days: 30
        
    - name: Create Release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          installers/*.dmg
          dist/*.dmg
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
